server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main #Rama de git
          uri: https://github.com/MaximilianoLutz/cloudStandardConfig.git
          search-paths: /config-data
  application:
    name: config-server